### ISSUE TITLE
Support for value type argument matchers

### ISSUE THREAD

**Issue by tjarvstrand** [mockito/mockito-scala#10]
Is there any way it would be possible to get out-of-the-box support for value types in argument matchers? Ie. allowing me to write eg. `any[MyType]` instead of `MyType(any[Int])`

That would be really nice!

**Comment by bbonanno** [comment]
@tjarvstrand I came here just to create this ticket!

Work in progress...

**Comment by bbonanno** [comment]
@tjarvstrand version 0.0.9 adds support for value classes

**Comment by mockitoguy** [comment]
Nice!
