### ISSUE TITLE
ReturnsSmartNulls returns empty string for `String` return type 

### ISSUE THREAD

**Issue by Krever** [mockito/mockito-scala#106]
When you mock method returning `String` and doesnt stub it, then you get empty stirng instead of null. 
Example:
```
class Test extends FunSuite with MockitoFixture {
  trait Foo {
    def foo: String
    def bar: Object
  }

  test("should faill") {
    val f1 = mock[Foo](DefaultAnswers.ReturnsSmartNulls)
    val f2 = Mockito.mock(classOf[Foo])
    println(f1.foo + "xxx")
    println(f1.bar + "xxx")
  }
}
```
this prints:
>xxx
>nullxxx

Its unsafe because one can forget about stubbing when not using `MockitoFixture` + its irregular.

**Comment by ultrasecreth** [comment]
That's how SmartNulls work in mockito-core, Strings and some other common Java data types are returned as empty. I agree it can be tricky, but getting a NullPointerException also is. I don't think there is a right answer here (at least not until inline-mocking becomes the default so we can mock final classes)

**Comment by Krever** [comment]
Ok, makes sense. I don't expect `NullPointerException` but rather smart null with `toString` defined as `"null"`.  But if its mockito-core thing than probably we cant do much. Thanks.

**Comment by ultrasecreth** [comment]
It could be changed, but the problem is that `String` is a final class, so you can't return a SmartNull, so it is either `""` or `null`
