### ISSUE TITLE
Strict Stub with AsyncIdiomaticMockito

### ISSUE THREAD

**Issue by rickyson96** [mockito/mockito-scala#108]
I want to create a unit test to test futures using AsyncWordSpec. I want to use Strict Stub method to reduce mocking boilerplate, following this example [here](https://github.com/mockito/mockito-scala#strict-mode). But I found that it is only available when using WordSpec. Is there anyway to do this asynchronously?

**Comment by rickyson96** [comment]
This code works well
```scala
class MySpec extends WordSpec with IdiomaticMockito {
  trait Setup {
    val myMock = mock[Sth]
    myMock.doSth shouldReturn "something"

    val myClass = new MyClass(myMock)
  }
  "some feature" should {
    "do something" in new Setup {
      myMock.doSthElse shouldReturn "something else"
      myClass.doSthElse shouldEqual "something else"
    }
  }
}
```
But this code doesn't work:
```scala
class MySpec extends AsyncWordSpec with AsyncIdiomaticMockito {
  trait Setup {
    val myMock = mock[Sth]
    myMock.doSthFuture shouldReturn Future("something")

    val myClass = new MyClass(myMock)
  }
  "some feature" should {
    "do something" in new Setup {
      myMock.doSthElseFuture shouldReturn Future("something else")
      myClass.doSthElseFuture.map { result =>
        result shouldEqual "something else"
      }
    }
  }
}
```
The async code produces following error
```
[error]  found   : MySpec.this.Setup
[error]  required: scala.concurrent.Future[org.scalatest.compatible.Assertion]
[error]       "do something" in new Setup {
```

**Comment by ultrasecreth** [comment]
Hi there, 

When you use a common `trait` for the test setup, said trait must extend `org.scalatest.FixtureContext`, otherwise you'll get that compile error.

That's a Scalatest requirement completely unrelated to mockito btw.

Also, the best place to find examples are the tests of mockito-scala, each implemented feature has one or more tests to prove they work ;)

**Comment by rickyson96** [comment]
I see. I know that it is from scalatest though but doesn't find the solution before.

So the said code will be like this (putting it here in case anyone face issue like this)
```scala
class MySpec extends AsyncWordSpec with AsyncIdiomaticMockito {
  trait Setup extends org.scalatest.FixtureContext {
    val myMock = mock[Sth]
    myMock.doSthFuture shouldReturn Future("something")

    val myClass = new MyClass(myMock)
  }
  "some feature" should {
    "do something" in new Setup {
      myMock.doSthElseFuture shouldReturn Future("something else")
      myClass.doSthElseFuture.map { result =>
        result shouldEqual "something else"
      }
    }
  }
}
```
>Also, the best place to find examples are the tests of mockito-scala, each implemented feature has one or more tests to prove they work ;)

I see, next time will read through those test for references :D

Thank you and kudos @bbonanno for this and the whole project. A great project for testing in scala! :+1:

**Comment by rickyson96** [comment]
Hi @bbonanno, I encountered some problem though
```scala
class AsyncIdiomaticMockitoTest extends AsyncWordSpec with Matchers with AsyncIdiomaticMockito {
  class Foo {
    def bar(a: String) = "bar"
  }

  class Baz {
    def fut(f: Foo) = Future {
      Thread.sleep(500)
      f.bar("in the future")
    }
  }

  trait newSetup {
    val foo: Foo = mock[Foo]
    // val baz = new Baz
  }
  "AsyncMockito" should {
    "work with real future assertions" in new newSetup with FixtureContext{
      // val foo = mock[Foo]
      val baz = new Baz

      foo.bar(*) shouldReturn "mocked"

      baz.fut(foo).map { r =>
        r shouldBe "mockedddd"
        foo.bar("in the future") was called
      }
    }
  }

}
```
I took those test from your spec and do some modification, but if I do it like the code above, it will produce false positive and the test will not fail. Did I miss something here?

**Comment by ultrasecreth** [comment]
Good catch, I was actually wrong, you can't use a Setup trait (or fixture-pattern, as it is known in the scalatest doc) with `AsyncSpecs`. 

I'll update the tests to reflect that, but in the meantime have a look at this [stackoverflow answer](https://stackoverflow.com/questions/46801118/how-to-use-fixture-context-objects-with-async-specs-in-scalatest)

**Comment by ultrasecreth** [comment]
I've updated the test to properly use the Setup trait.
Is not the only way to do so, but I've chosen it as it let you access all the `val`s and `def`s in the `trait` with little boilerplate.

```scala
class AsyncIdiomaticMockitoTest extends AsyncWordSpec with Matchers with AsyncIdiomaticMockito {

  class Foo {
    def bar(a: String) = "bar"
  }

  class Baz {
    def fut(f: Foo) = Future {
      Thread.sleep(500)
      f.bar("in the future")
    }
  }

  class Setup {
    val foo: Foo = mock[Foo]
  }

  "AsyncMockito" should {
    "work with real future assertions" in {
      val setup = new Setup
      import setup._

      val baz = new Baz

      foo.bar(*) shouldReturn "mocked"

      baz.fut(foo).map { r =>
        r shouldBe "mocked"
        foo.bar("in the future") was called
      }
    }
  }
}
```

**Comment by rickyson96** [comment]
I see, that would do the trick. Thank you!
