### ISSUE TITLE
Release for Scala 2.13.0.

### ISSUE THREAD

**Issue by erikvanoosten** [mockito/mockito-scala#119]
Scala 2.13.0 is out! 🎉

**Comment by ultrasecreth** [comment]
Yes!
I’m waiting for my 4 dependencies to be out first

**Comment by ultrasecreth** [comment]
Depends on

- [x] https://github.com/typelevel/cats/issues/2883
- [x] https://github.com/scalatest/scalatest/issues/1601
- [x] https://github.com/scalaz/scalaz/pull/2064
- [x] https://github.com/etorreborre/specs2/pull/746
