### ISSUE TITLE
`AccessControlException` thrown when using Mockito.spy(...)

### ISSUE THREAD

**Issue by Aghmat-Abrahams-IR** [mockito/mockito-scala#122]
Hi I'm getting the following error message when spying on a `org.apache.spark.streaming.scheduler.StreamingListener`:

```
 java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
```

The issue could be solved by adding the following line to your `/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/jre/lib/security/java.policy` file -> `permission javax.management.MBeanTrustPermission "register";` under the grant section.

I was wondering if there was a programatic solution.

**Comment by Aghmat-Abrahams-IR** [comment]
A little context. I'm writing an integration test for a Spark streaming job and am using spies to verify if a batch has completed. 

I am using `MacOS 10.14.4` and our CI server uses `CentOS Linux release 7.6.1810 (Core)`. This issue occurs under both environments.

I found a single alternative to manually adding the permissions and that is using [securemock](https://github.com/elastic/securemock). Securemock looks pretty abandoned though.

**Comment by ultrasecreth** [comment]
Hi, that's an interesting one, can you tell me which spark dependencies (and anaything else I need) are you using?

**Comment by Aghmat-Abrahams-IR** [comment]
Hi, sure mainly kafka010, KuduContext and and KuduClient. Here's a full list of my imports and versions:

```
import com.typesafe.config.{Config, ConfigFactory}
import org.apache.kudu.client.KuduClient
import org.apache.spark.streaming.scheduler.StreamingListenerBatchCompleted
import org.junit.runner.RunWith
import org.mockito.Mockito._
import org.mockito.{ArgumentCaptor, Mockito}
import org.scalatest.junit.JUnitRunner
import org.scalatest.{BeforeAndAfterAll, FunSuite}
import org.apache.avro.generic.IndexedRecord
import org.apache.kafka.clients.consumer.ConsumerRecord
import org.apache.kafka.common.TopicPartition
import org.apache.kafka.common.record.TimestampType
import org.apache.kudu.client.CreateTableOptions
import org.apache.kudu.spark.kudu.KuduContext
import org.apache.log4j.Logger
import org.apache.spark.rdd.RDD
import org.apache.spark.sql.catalyst.parser.CatalystSqlParser
import org.apache.spark.sql.types.{StructField, StructType}
import org.apache.spark.sql.{DataFrame, SQLContext, SparkSession}
import org.apache.spark.streaming.dstream.InputDStream
import org.apache.spark.streaming.kafka010.ConsumerStrategies.Subscribe
import org.apache.spark.streaming.kafka010.KafkaUtils.createDirectStream
import org.apache.spark.streaming.kafka010.LocationStrategies.PreferConsistent
import org.apache.spark.streaming.kafka010.{CanCommitOffsets, ConsumerStrategy, HasOffsetRanges}
import org.apache.spark.streaming.{Seconds, StreamingContext}
import org.apache.spark.{SparkConf, SparkContext}

import scala.collection.JavaConverters._
import scala.collection.mutable
```

```
scalaVer="2.11.12"
scalaCompatVer="2.11"
scalatestVer = "3.0.3"
kafkaVer = "0.10.0.1"
sparkVer = "2.2.0"
confluentVer = "3.3.1"
avroVer = "1.8.2"
typesafeConfigVer = "1.2.1"
kuduVer = "1.7.0-cdh5.15.0"
mockitoVer = "1.5.7"
```

**Comment by Aghmat-Abrahams-IR** [comment]
I'll could also simplify + generify the Job and test if it will help since there is some propriety code.

**Comment by ultrasecreth** [comment]
That would be brilliant, some piece of code I can copy and paste (or a small github repo with a failing test) to easily reproduce the issue would help a lot as I don't know much about Spark

**Comment by Aghmat-Abrahams-IR** [comment]
Ok cool, will do

**Comment by Aghmat-Abrahams-IR** [comment]
Have been a bit preoccupied, will try to get sample code done by the end of the week

**Comment by ultrasecreth** [comment]
No worries, after thinking about it I think the best option is a github repo that reproduces the issue so we're sure that libs and dependencies work as expected

**Comment by Aghmat-Abrahams-IR** [comment]
👍

**Comment by Aghmat-Abrahams-IR** [comment]
My bad, turns out it was not Mockito causing the issue. A custom `SecurityManager` was the root cause, I should have caught it sooner. This issue can be closed.
