### ISSUE TITLE
Mocking any instance of class

### ISSUE THREAD

**Issue by nickresnick** [mockito/mockito-scala#123]
Less of an issue and more of a question: Is it possible to mock any instance of a class, not just a single instance? 

Use case here is that I have a class with a `copy` method that creates a new instance of the class with extra members. I want to be able to spy on copied instances that are created inside of various functions.

**Comment by Krever** [comment]
I don't know of any out of the box solution, but could you delegate/override/mock the copy method to produce spies/mocks?

**Comment by nickresnick** [comment]
Yeah that's what i was thinking. I'll give it a shot, thanks.

**Comment by ultrasecreth** [comment]
Why would you be mocking data in the first place?
