### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by evertones** [mockito/mockito-scala#141]
I found a broken link in the documentation - [main page in GitHub](https://github.com/mockito/mockito-scala/blob/release/1.x/README.md).
It is in the text - *Note: For more examples and use cases than the ones shown below, please refer to the library's tests* - that points to an invalid URL.

Unfortunately, I could not figure out which URL it should be to submit a PR.

Currently it points to [this link](https://github.com/mockito/mockito-scala/blob/release/1.x/core/src/test), which returns `404` error.

A few links I thought could be related:
- https://github.com/mockito/mockito-scala/tree/release/1.x/scalatest/src/test
- https://github.com/mockito/mockito-scala/tree/release/1.x/scalaz/src/test
- https://github.com/mockito/mockito-scala/tree/release/1.x/specs2/src/test

Hope someone else can fix or tell me the correct link to submit a PR.

**Comment by ultrasecreth** [comment]
Hi!
Good catch, most of the library tests were moved to the scalatest module as they were scalatest based, but it would be good to also add links to the specs2, cats, and scalaz on each one of their sections.

If you fancy please raise a PR, otherwise I'll do it in a few days.

Thanks!

**Comment by ultrasecreth** [comment]
Solved by #143
