### ISSUE TITLE
Stubbing with reordered named parameters doesn't work and produces a cryptic error

### ISSUE THREAD

**Issue by einholen** [mockito/mockito-scala#145]
Hello!

When migrating from older `mockito-core` (1.x) with specs2 wrappers to `mockito-scala`, a few of our existing stubbings failed to compile.

Here's an example that doesn't compile (assuming `org.mockito.scalatest.IdiomaticMockito`). Note that in the stubbing, `defaultParam2` and `defaultParam1` are used in a different order than in the signature.

```scala
import org.mockito.scalatest.IdiomaticMockito
import org.scalatest.FlatSpec

trait MyService {
  def bar(a: String, defaultParam1: Boolean = false, defaultParam2: Int = 1): String
}

class MyServiceSpec extends FlatSpec with IdiomaticMockito {
  it should "correctly stub an invocation with concrete values" in {
    val myService = mock[MyService]
    
    myService.bar("hello", defaultParam2 = 3, defaultParam1 = true) returns "hello3true"
    
    myService.bar("hello", defaultParam2 = 3, defaultParam1 = true)
  }
}
```

Error message is not helpful at all, I spent a good amount of time figuring out what's wrong with my signature before I was able to narrow down the root cause to named params:

```
[error] exception during macro expansion: 
[error] java.lang.Exception: Couldn't recognize MyServiceSpec.this.StubbingOps[String]({
[error]   <artifact> val x$1: String = "hello";
[error]   <artifact> val x$2: Int = 3;
[error]   <artifact> val x$3: Boolean = true;
[error]   myService.bar(x$1, x$3, x$2)
[error] }).returns
[error] 	at org.mockito.WhenMacro$.shouldReturn(WhenMacro.scala:39)
[error]     myService.bar("hello", defaultParam2 = 3, defaultParam1 = true) returns "hello3true"
[error]                                                                     ^
[error] one error found
```

Plain Mockito seems to work correctly at runtime in this case (`when(...).thenReturn(...)`).

Is there a way to make it work or at least change the error message so it would give a hint about what's wrong?

Thanks!

**Comment by ultrasecreth** [comment]
Hi!

Thanks for reporting this, I'll take a look :)
