### ISSUE TITLE
Documentation for mockito-core and mockito-scala dependency order

### ISSUE THREAD

**Issue by dpfeiffer** [mockito/mockito-scala#16]
I just saw `mock[X]` randomly working and not (`ArgumentsProcessor.extractors` not found) which seems to be related to `mockito-scala` overwriting that class.

If I remember correctly to make this work the `mockito-core` dependency has to be declared explicitly before the `mockito-scala` dependency like

```
libraryDependencies ++= Seq(
  "org.mockito"              % "mockito-core"             % "2.21.0" % Test,      
  "org.mockito"              %% "mockito-scala"         % "0.0.13" % Test
)
```

Maybe I am missing something but if my assumption is right I suggest to add that information to the readme to avoid others running into the same issue.

**Comment by bbonanno** [comment]
Hi @dpfeiffer, mockito-scala will pull the appropriate mockito-core version, so you shouldn't need to declare it at all, but I agree, it currently relies on a class loader hack, so if you do declare the mockito-core dependency the order matters, I've added a note to the documentation

Many thanks for the feedback

**Comment by dpfeiffer** [comment]
Hi @bbonanno, thanks for your quick reply, actually putting an explicit `mockito-core` dependency in was just an attempt to fix loading the wrong (the one from `mockito-core`) `ArgumentProcessors` class and therefore getting a field not found. (`extractors`). I thought that declaring the dependency explicitly might solve that issue but it didn't.

Could it be that by declaring scalatest (which has a transitive optional dependency to mockito-core) after mockito-scala leads to mockito-core being after mockito-scala on the classpath (randomly)?

I will let you know if I can find out more.

**Comment by bbonanno** [comment]
That could be it, when I tried it in a third project I was declaring it as the last test dependency (just by chance) so I've never seen the issue, please try declaring it as the last one and/or exclude scalatest's transitive dependency on mockito

I'd do some investigation tonight to see if I can get to the bottom of the issue

**Comment by bbonanno** [comment]
Please refer to https://github.com/mockito/mockito-scala/issue_comments#issuecomment-411869701

**Comment by bbonanno** [comment]
please refer to #18
