### ISSUE TITLE
proposal: Allow partial function to stub `answers`

### ISSUE THREAD

**Issue by gervaisb** [mockito/mockito-scala#188]
At this time, to stub one answer we have to provide a function. But in some cases we have to match on some parameters to compute the answer.

    mocked.doSomething(*, *, *) answers { (s:String, opt:Option[Int], b:Boolean) => 
      opt match {
        case Some(number) if number > 0 => ...
        case None => ...
        case _ => ???
      }
    }

Using a partial function would simplify our code:

    mocked.doSomething(*, *, *) answers {
      case (_, Some(number), _) => if number > 0 => ...
      case (_, None, _) => ...
    }
   // Where `case _` would return the default answer

**Comment by ultrasecreth** [comment]
Hi @gervaisb, I had a play with it a while ago and dropped it for some reason I can't remember.
I'll revisit it now I'm (hopefully) wiser and see if I can get it to work this time :)

**Comment by ultrasecreth** [comment]
I could get something like this working, sadly the compiler is not smart enough to overload standard functions with partial functions, so the method name has to be different

```scala
val org = mock[Org]

org.doSomethingWithThisInt(*) answersPF {
  case i: Int => i * 10 + 2
}
org.doSomethingWithThisIntAndString(*, *) answersPF {
  case (i: Int, s: String) => (i * 10 + s.toInt).toString
}
org.doSomethingWithThisIntAndStringAndBoolean(*, *, *) answersPF {
  case (i: Int, s: String, true) => (i * 10 + s.toInt).toString + " verdadero"
  case (i: Int, s: String, false) => (i * 10 + s.toInt).toString + " falso"
}

org.doSomethingWithThisInt(4) shouldBe 42
org.doSomethingWithThisIntAndString(4, "2") shouldBe "42"
org.doSomethingWithThisIntAndStringAndBoolean(4, "2", v3 = true) shouldBe "42 verdadero"
org.doSomethingWithThisIntAndStringAndBoolean(4, "2", v3 = false) shouldBe "42 falso"
```
