### ISSUE TITLE
bug: `argMatching` with `answers`

### ISSUE THREAD

**Issue by gervaisb** [mockito/mockito-scala#191]
Hello,

I may use this library in an unexpected way but it seems that `argMatching` is not working in all cases. 

I have a `Service` with one method `init` and one `execute(s:State, p:Parameter)`. 
 + The `init` method returns the `State` and is mocked
 + The `execute` method is stubbed with `answers`

My test call the `init`method and then `execute` two times and verify that `service.execute(*, argMatching({case ExpectedParameterType(_) => })) was called`. However it fail with:

> Argument(s) are different! Wanted:
> service.execute(
>     <any>,
>     argMatching(...)
> );
> -> at example.ServiceSpec.$anonfun$new$4(ServiceSpec.scala:27)
> Actual invocations have different arguments:
> service.init(
>     
> );
> -> at example.ServiceSpec.$anonfun$new$3(ServiceSpec.scala:23)
> service.execute(
>     My mock for State,
>     OtherParameterType(Other)
> );
> -> at example.ServiceSpec.$anonfun$new$3(ServiceSpec.scala:24)
> service.execute(
>     My mock for State,
>     ExpectedParameterType(Expected)
> );
> -> at example.ServiceSpec.$anonfun$new$3(ServiceSpec.scala:25)
> 
> 	at example.ServiceSpec.$anonfun$new$4(ServiceSpec.scala:27)
> 	at example.ServiceSpec.verification(ServiceSpec.scala:7)
> 	at example.ServiceSpec.$anonfun$new$3(ServiceSpec.scala:27)

As you can see the second invocation of `execute` is the expected one. And the partial function in `argMatching` is defined for the argument. Am I doing something wrong ?

Here is a sample project to reproduce it : https://github.com/gervaisb/mockito-scala_191

**Comment by ultrasecreth** [comment]
I'll take a look as soon as I can

**Comment by gervaisb** [comment]
Do you have any estimates ? It is quite blocking for us. 

I could create a test double for the service but this is a huge amount of work (we have ~40 "services" with the same pattern).

**Comment by ultrasecreth** [comment]
ok, this one was easy :)

you got the verification wrong, try with

```scala
subject.execute(*, argMatching({ case _: ExpectedParameterType => })) was called
```

in short, the partial function has to match just that argument, for some reason your partial function was looking for a `Tuple3`  (`case (_, _: ExpectedParameterType, _)`)

**Comment by gervaisb** [comment]
Yes, sorry. This was an issue in my sample. My matching is more complex than that, it is a copy-paste error. 

The sample project is passing while my real tests are still failing. However the partial function used in `argMatching` is defined for the receive argument.. If the partial function is defined and executed, how can it fail ?

But because the sample is passing I guess it is an issue on my side. Sorry for the inconvenience

**Comment by ultrasecreth** [comment]
I'd say test the partial function independently and see if `isDefined()` returns what you expect

**Comment by gervaisb** [comment]
@bbonanno can we continue this discussion on this StackOverflow thread https://stackoverflow.com/questions/59666468/mockito-scala-verify-method-invocation ?

(And delete this fake Issue)

**Comment by ultrasecreth** [comment]
@gervaisb  deal
