### ISSUE TITLE
Public release of mockito-scala

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito-scala#2]
This ticket tracks work needed to release mockito-scala

- [x] - @bbonanno, can you make the artifacts in "target" directory have the dir structure as expected in a Maven repository? It is needed so that when we publish to Bintray the artifacts will be neatly resolvable by ivy/SBT, Maven or Gradle.
- [x] - @mockitoguy - configure Bintray publications
- [x] - @mockitoguy - update the README (if needed)
- [x] - push & announce

**Comment by bbonanno** [comment]
Isn't that the purpose of the ```dist``` folder? if so it works already

**Comment by mockitoguy** [comment]
@bbonanno, check out the new PR, we should be able to publish to Bintray soon.

Can you explain how the target/dist directories work? Are those standard dirs in SBT projects? I'm considering if we should put all the outputs inside the "build" dir for clarity. However, if they are standard convention of SBT Scala projects, let's just keep it simple.

**Comment by bbonanno** [comment]
@mockitoguy It's not 'standard' to use the dist directory, but it's what play-parsec is configured to do, so I did it that way.
build.sh specifies that here ```set every publishTo := Some(Resolver.file("local-repo", file("dist")))``` and then there is a declaration in shipkit.gradle ```ext.releaseSpec = fileTree("dist")``` that I guess is to instruct it to use that dir
We can put everything in target by changing build.sh, I don't have a strong opinion about it, I kinda like a separate dir for the releasable files, but if you'd prefer to use target I'm totally happy with it as well.

**Comment by mockitoguy** [comment]
Thank you for information! The SBT build in play-parseq was created by original authors and I did not dig into its design. From the standpoint of SBT, is there are reason we do 'rm -rf dist' in 'clean.sh' and 'build.sh'?

To keep the house tidy, I'm in favor to changing "dist" -> "target/dist" and fixing "clean.sh" + "./gradlew clean" so that it actually cleans up all build outputs. However, let's not block the PR on this.

**Comment by mockitoguy** [comment]
Good news :)

```
[performRelease] Release shipped!
[performRelease]     - Publication repository: https://bintray.com/mockito/maven/mockito-scala/
[performRelease]     - Release notes:          https://github.com/mockito/mockito-scala/blob/master/docs/release-notes.md
[performRelease] 
[performRelease] BUILD SUCCESSFUL in 20s
[performRelease] 12 actionable tasks: 12 executed
  External process [performRelease] completed.
  Release 0.0.3 was shipped! Thank you for using Shipkit!
BUILD SUCCESSFUL in 33s
1 actionable task: 1 executed
```

@bbonanno, ready to include 0.0.3 in JCenter? Once we do it, we cannot remove the artifact. We will also work on Maven Central.

**Comment by bbonanno** [comment]
@mockitoguy Great news!!!

I've created 2 new PRs, one is to move the dist folder inside target

The other one is a feature I'd like to have in the initial release, but that I had to hack a bit to make it work, I'm willing to live with the hack unless you can think in a better way to do it. Otherwise I'd merge it like this and we can discuss what would be the right way to do it when mockito-core supports it (and if you tell me what to do I can do those changes myself and create a PR for you guys)

0.0.3 should be fine as a first release in case you think the ArgumentProcessor PR shouldn't be merged, otherwise I'd merge it and publish 0.0.4 with it

**Comment by mockitoguy** [comment]
Let's work on the by-name feature after the initial GA. The binaries are already released to Bintray so people can use them:
 - https://dl.bintray.com/mockito/maven/org/mockito/mockito-scala_2.12/
 - https://bintray.com/mockito/maven/mockito-scala/

Are you ready to ship to Maven Central? If I hear from you, I will pull the trigger.

**Comment by bbonanno** [comment]
@mockitoguy go for it!

I have a PR ready (#6) for when that's done so we add the links to Maven and Bintray to the README

**Comment by mockitoguy** [comment]
Sounds good! I requested "mockito-scala" package to be included in JCenter (first step to Maven Central publications).

**Comment by bbonanno** [comment]
@mockitoguy Great!
