### ISSUE TITLE
"aMock wasNever called" treats mocks defined inside fixture objects as method calls

### ISSUE THREAD

**Issue by einholen** [mockito/mockito-scala#212]
We use fixture objects (not traits) and `org.scalatest.fixture._` specs, so mocks are provided into the test like so

```scala
class Fixture {
  val service = mock[Service]
}

// ...

"mySpec" should "test something" in { f: Fixture =>
  f.service wasNever called
}
```

`VerifyMacro` treats `f.service` as a method call, and I get a `NotAMockException`.

I can think of a few ways to solve it:

1. Define a different syntax for verifications on a mock vs a method call. Maybe `aMock wasNever interactedWith`, or even just expose the regular `verifyNoInteractions`?

2. I don't think we can distinguish a method call from a field access using quasiquotes - `q"$a.$b"` matches both if the method has no parens or type args. Here's what I think we could do, however:
    - Method calls with parens is always `Apply` tree
    - Field access or no-paren method calls is always `Select`
    
    We could match against these types specifically, and in the case of `Select`, check if the penultimate identifier is a mock - and if so, treat it as a method call, otherwise as field access.
    To illustrate:
    ```scala
    fixture.aMock wasNever called
    ```
    translates into
    ```scala
    if (mockingDetails(fixture).isMock) verify(fixture, never()).aMock
    else verifyZeroInteractions(fixture.aMock)
    ```

3. (Kinda orthogonal to the above) In Expect DSL, define `on` for mock objects on the right side, and that would be distinct from `to` which only expects method calls, so we'd use
    ```scala
    expect no calls on aMock
    ```
    instead of
    ```scala
    expect no calls to aMock
    ```
    `on` vs `to` would be such a subtle change though so I can imagine errors in these lines be frustrating to diagnose... Maybe a better alternative would be `expect no interactions with aMock`, or again, just expose the vanilla `verifyNoInteractions`/alias it to `expectNoInteractions`

**Comment by ultrasecreth** [comment]
What if you add a line at the beggining of the test like `import f.*` or `import f.service`? That would allow the macro to understand what's going on. 
I know is not a solution but it should work as a workaround.

I like tha macro idea, we can give it a go!

same for the new syntax, works for me!

Also out of curiosity, is there any reason to favour classes traits?

**Comment by einholen** [comment]
Nope, importing doesn't help - it desugars right back into `f.service`.

This works but it's too tedious to do everywhere:
```scala
val service = f.service
service wasNever called
```
Using `verifyZeroInteractions(f.service)` directly is a sufficient workaround for now.

Well, I think the main reason to use fixture objects was that they allow for fixture cleanup (ie terminate actor system) while keeping the context confined to a single test. The alternative is to use shared state but it's kinda discouraged in Scalatest.

Cool, I have some code for the Expect DSL stuff I talked above, I can give the rest a go closer to the weekend if you're busy :)

**Comment by ultrasecreth** [comment]
I'll play around with getting the macro to support this, you can play with the Expect DSL as it's your baby ;)

**Comment by ultrasecreth** [comment]
@einholen could you post a complete example, I came up with this (never used fixtures like this before) and it passes like charm

```scala
import org.mockito.scalatest.IdiomaticMockito
import org.scalatest.{Outcome, fixture}
import org.scalatest.matchers.should.Matchers

class IdiomaticMockitoFixtureClassTest extends fixture.FlatSpec with IdiomaticMockito with Matchers {
  class Foo {
    def bar(a: String) = "bar"
  }

  class FixtureParam {
    val foo: Foo = mock[Foo]
  }

  def withFixture(test: OneArgTest): Outcome = {
    val theFixture = new FixtureParam
    withFixture(test.toNoArgTest(theFixture))
  }

  "Mockito" should "work on tests with fixture objects" in { f: FixtureParam =>
    "mocked" willBe returned by f.foo.bar("pepe")

    f.foo.bar("pepe") shouldBe "mocked"

    f.foo.bar("pepe") was called

    f.foo wasNever calledAgain
  }
}
```

**Comment by einholen** [comment]
Sure!
It doesn't necessarily depend on the spec being a fixture spec - it can be reproduced by using _any_ object to store the mock.

Given the context of `PostfixVerificationsTest.scala`:

```scala
val fixture = new SetupNeverUsed {}

"check a mock had no interactions (with fixture object)" in {
  fixture.org wasNever called

  a[NoInteractionsWanted] should be thrownBy {
    fixture.org.baz

    fixture.org wasNever called
  }
}
```

yields

```
Argument passed to verify() is of type $anon$3 and is not a mock!
```

**Comment by einholen** [comment]
Ah, I assumed `wasNever called` and `wasNever calledAgain` would behave identically, but just realized there's no `calledAgain` for method calls so in your test case it drops down to `q"$_.VerifyingOps[$_]($obj).wasNever($called)($_)"` and works as intended. But `wasNever called` trips on the match before this one

**Comment by ultrasecreth** [comment]
Gotcha
