### ISSUE TITLE
 org.mockito.scalatest.Mockito does not exist

### ISSUE THREAD

**Issue by wsargent** [mockito/mockito-scala#219]
The documentation says 

> When using Scalatest and org.mockito.scalatest.Mockito this is the default mode, you can override the strictness to be lenient by doing val strictness: Strictness = Strictness.Lenient The implication under the hood is that every test will run inside a MockitoScalaSession, so all of them will run in Strict Stub mode.

https://github.com/mockito/mockito-scala/blame/release/1.x/README.md#L250

However, there is no `org.mockito.scalatest.Mockito` in 1.13.1, so it can't be added.

https://github.com/mockito/mockito-scala/tree/release/1.x/scalatest/src/main/scala/org/mockito/scalatest

**Comment by ultrasecreth** [comment]
Yeah, I thaink that was a renaming that never happened...
`org.mockito.scalatest.IdiomaticMockito` is the trait you should use, `org.mockito.scalatest.Mockito` could be added, but it would just be an alias of `org.mockito.scalatest.IdiomaticMockito`, so not sure if it has any value.

I'm torn in between updating the README to show `org.mockito.scalatest.IdiomaticMockito` or add a simple `org.mockito.scalatest.Mockito` as an alias of `org.mockito.scalatest.IdiomaticMockito`, what do you think?

**Comment by ultrasecreth** [comment]
README updated

**Comment by wsargent** [comment]
I'd prefer to just point to IdiomaticMockito rather than add a class.  I don't have an objection to the name.
