### ISSUE TITLE
Consider releasing less often

### ISSUE THREAD

**Issue by erikvanoosten** [mockito/mockito-scala#233]
I deeply appreciate the attention given to this project. Therefor I waited long with this request: can you please consider releasing less often, perhaps at most once a week? Because of scala steward each release causes volunteers doing manual approval actions in many projects.
Many thanks for making my favorite mocking library!

**Comment by ultrasecreth** [comment]
@erikvanoosten that's a good point, a big chunk of my releases are driven by scala-steward too, I guess I can wait and merge them all at once every now and then

Maybe we should request a feature to scala-steward so they also do a single PR with updates every week or whatever? so we all have less load of releases that just upgrade dependencies.

**Comment by erikvanoosten** [comment]
Hi @bbonanno such a feature already exists! See here: https://github.com/fthomas/scala-steward/blob/master/docs/repo-specific-configuration.md
