### ISSUE TITLE
Mockito throws NPE when using AnyVal derived types in mocked methods

### ISSUE THREAD

**Issue by longliveenduro** [mockito/mockito-scala#244]
Mockito throws NPE when using AnyVal derived types in mocked methods

See https://github.com/longliveenduro/mockito-anyval-bug to reproduce.

See also https://gist.github.com/kasia-kittel/3255fd5dc5f8f861f4e02bb966302c1c

**Comment by ultrasecreth** [comment]
99% sure that's because you must specify the type when using any matchers that replace a value class, check the docs here: https://github.com/mockito/mockito-scala#value-class-matchers

**Comment by longliveenduro** [comment]
Cheers that works!
