### ISSUE TITLE
Publish version for Scala 2.11 please?

### ISSUE THREAD

**Issue by jozic** [mockito/mockito-scala#25]

**Comment by bbonanno** [comment]
This isn't an easy one as if I remember correctly we rely on some 2.12 features, but I'll give it a go to see what happens!

**Comment by bbonanno** [comment]
Scala 2.11 support was added by #26

**Comment by jozic** [comment]
thanks

**Comment by bbonanno** [comment]
Please read https://github.com/mockito/mockito-scala#notes-for-scala-211 as a couple of things are not supported in Scala 2.11
