### ISSUE TITLE
How do I specify that a mock has no interactions after a given timeout in mockito-scala?

### ISSUE THREAD

**Issue by longliveenduro** [mockito/mockito-scala#253]
I can't find a nice Scala DSL way to specify that a mock was not called after a specified duration.

Something like

aMock wasNever calledAgain after 2.seconds
The doc also doesn't mention anthing. https://github.com/mockito/mockito-scala

Do I have to fall back to standard mockito verification?

https://stackoverflow.com/questions/62410513/how-do-i-specify-that-a-mock-has-no-interactions-after-a-given-timeout-in-mockit

**Comment by ultrasecreth** [comment]
I'm not aware of any for doing that even in Java mockito, what you can do is assert for specific methods, and the Scala DSL for that would be something like

```scala
aMock.foo wasCalled 0.times.within(2.seconds)
// or
aMock.foo wasCalled 0.times.after(2.seconds)
```

What you can't do is assert over the whole object and provide a timeout with mokito afaik.

In any case, I'll side with one of the answers in StackOverflow and use Scalatest for this kind of time related verifications, I added this to the DSL for completeness of the API, but hadn't had the best experience with those, to the point I had to remove my own tests for it as the build was super flaky.

**Comment by longliveenduro** [comment]
In Mockito it is documented to be done like this, on a method invocation level

`verify(mock, timeout(100).never()).bar();`

https://www.javadoc.io/doc/org.mockito/mockito-core/2.2.9/org/mockito/verification/VerificationWithTimeout.html

See also the text hint below the code example:
"This is similar to after() except this assertion will immediately pass if it becomes true at any point, whereas after() will wait the full period. Assertions which are consistently expected to be initially true and potentially become false are deprecated below, and after() should be used instead."

**Comment by longliveenduro** [comment]
You are right, sorry, seems there is no assert over the whole mock with a timeout/after.

**Comment by longliveenduro** [comment]
Just as a suggestion: Maybe leave out the dependency on Scalatest. I personally love it, but I am currently working in a project using an old Specs2 version. So I would have a hard time (for good reasons) arguing to add a dependency on Scalatest just for this.

**Comment by ultrasecreth** [comment]
Exactly, but even if there was any, I'd still recommend to use Scalatest for that(or Specs2, I'm sure it has a way to do that).

Mockito-Scala has integrations for both, Scalatest and Specs2, so you don't need to add Scalatest in your project, just use whatever tool Specs2 has to deal with async verifications :)

**Comment by longliveenduro** [comment]
Unfortunately they use a very old version of Specs2 (2.5) and made a good job not to be easy upgradeable. So I will probably use the old Specs2 method here, but using any more recent Specs2 integration version of mockito-scala brings up probably more problems, which I currently try to avoid.

I am currently trying to establish a step-by-step approach to upgrade the libs as a big bang is not feasible in this project.

**Comment by ultrasecreth** [comment]
Fair enough
