### ISSUE TITLE
How to mock scala obejct 

### ISSUE THREAD

**Issue by rhh777** [mockito/mockito-scala#303]
hi , I tried to mock Scala with 1.16.0, but the result was an error. This is my code. What's wrong with it? thanks
my pom
<dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-scala_2.11</artifactId>
            <version>1.16.0</version>
        </dependency>
my scala 2.11.8
my obejct 

object FooObject {
    def simpleMethod: String = "not mocked!"
}

object MockObject {
    def main(args: Array[String]): Unit = {
        withObjectMocked[FooObject.type] {
            FooObject.simpleMethod returns "mocked!"
            //or
            //when(FooObject.simpleMethod) thenReturn "mocked!"
            FooObject.simpleMethod ==  "mocked!"
        }
        FooObject.simpleMethod == "not mocked!"
    }
}

error:

>`Exception in thread "main" org.mockito.exceptions.base.MockitoException: 
Cannot mock/spy class FooObject$
Mockito cannot mock/spy because :
 final class
	at MockObject$.main(MockObject.scala:10)
	at MockObject.main(MockObject.scala)
`

**Comment by ultrasecreth** [comment]
It seems I forgot to mention it in the docs, you need to use the inline mock maker for this to work

**Comment by rhh777** [comment]
> It seems I forgot to mention it in the docs, you need to use the inline mock maker for this to work

Sorry, I have checked the test package, I still don't quite understand what inline Mock Maker is, can you provide an example? thanks

**Comment by LanceEa** [comment]
@QuietHR  - I was able to get it to work once I added MockMaker plugin per the release notes on Mockito - [Mock Maker](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#mock-the-unmockable-opt-in-mocking-of-final-classesmethods)

<img width="806" alt="Screen Shot 2020-10-21 at 9 27 37 AM" src="https://user-images.githubusercontent.com/8103374/96733984-ad0cbe80-137f-11eb-9a18-bd08c3b40d34.png">

**Comment by rhh777** [comment]
> @QuietHR - I was able to get it to work once I added MockMaker plugin per the release notes on Mockito - [Mock Maker](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#mock-the-unmockable-opt-in-mocking-of-final-classesmethods)
> 
> <img alt="Screen Shot 2020-10-21 at 9 27 37 AM" width="806" src="https://user-images.githubusercontent.com/8103374/96733984-ad0cbe80-137f-11eb-9a18-bd08c3b40d34.png">

<img width="1542" alt="图片" src="https://user-images.githubusercontent.com/41908930/96823137-5a560400-145e-11eb-876c-67800ac41f5e.png">
Thank you very much. According to your method, the mock succeeded ~

**Comment by ultrasecreth** [comment]
Would you mind guys raising a PR to add those instructions on the README? I'm super busy these days but I can easily merge a PR :)

**Comment by rhh777** [comment]
> Would you mind guys raising a PR to add those instructions on the README? I'm super busy these days but I can easily merge a PR :)

Sure. It's my pleasure
