### ISSUE TITLE
MockitoFixture cannot be used with ResetMocksAfterEachTest

### ISSUE THREAD

**Issue by Krever** [mockito/mockito-scala#32]
> overriding method withFixture in trait MockitoFixture of type (test: IdentificationServiceSpec.this.NoArgTest)org.scalatest.Outcome;
> method withFixture in trait ResetMocksAfterEachTest of type (test: IdentificationServiceSpec.this.NoArgTest)org.scalatest.Outcome has weaker access privileges; it should be public

sorry that I only report issues instead of fixing them immediately in a PR, Im low on time ;/

**Comment by bbonanno** [comment]
That's all right

I haven't put much effort in this one (maybe I just should document it doesn't work) as both modes are somehow incompatible

This trait is aim for people that **must** declare their mocks outside the test scope, and as we discussed in #31 the session basically requires the mock to created as part of each test and not as part of the test class

I'm going to think if there is a fancy way to combine both, but tbh, I don't think the use cases overlap, if you were forced to have mocks as class instances then there isn't that much you can do about it

What do you think? is there any use-case in where it make sense to have both class and test level mocks?

**Comment by Krever** [comment]
Nope, your reasoning is fully correct, I would just mention it explicitly in the docs :)

**Comment by bbonanno** [comment]
Fixed on #30
