### ISSUE TITLE
Migrate to GH actions

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito-scala#324]
Migrating to GH actions improves the CI/CD experience (the UI is cleaner, it's easier to analyze logs, the jobs start quicker).

Mockito (https://github.com/mockito/mockito/issues/2080) and mockito-testng (https://github.com/mockito/mockito-testng/pull/17) projects have already migrated to GH Actions.

**Comment by ultrasecreth** [comment]
Nice, I'll have a look this weekend I hope
