### ISSUE TITLE
Captor macro uses deprecated JavaConverters Scala 2.13

### ISSUE THREAD

**Issue by diversit** [mockito/mockito-scala#360]
In a Scala 2.13 project,
when creating an ArgCaptor for a Value Class
the compiler reports error: `object JavaConverters in package collection is deprecated (since 2.13.0): Use `scala.jdk.CollectionConverters` instead`

which is caused by this line in the Captor macro implementation (I think): https://github.com/mockito/mockito-scala/blob/6d9e26423dd4e1551994d86f95801e5048b8db07/macro/src/main/scala/org/mockito/captor/Captor.scala#L81

**Comment by ultrasecreth** [comment]
Cool, that should be an easy fix, will have a look as soon as I can

**Comment by diversit** [comment]
Thanks!
I had also looked on a solution but yours is much more elegant.
Looking forward to a new release.
