### ISSUE TITLE
scala 2.13 array passed as Seq is seen as variarg 

### ISSUE THREAD

**Issue by borissmidt** [mockito/mockito-scala#378]
In case we have a class extending a trait with final def mockito seems unable to get the right `methodsToProcess` and sees a wrapped array as a variarg. This also messes up the `captor` which sees it as multiple invocations for some odd reason.
```scala
case class Job()
trait Logs {
  final def info(s: String): Unit = { println("my hello") }
}
class Repository extends Logs {
  def writeJobs(jobs: Seq[Job]): Future[Unit] = Future.successful(())
}

    val repository = mock[Repository]
    when(repository.writeJobs(*)).thenReturn(Future.successful(()))
    repository.writeJobs(ArraySeq.unsafeWrapArray(Array(Job(), Job(), Job())))
    verify(repository).writeJobs(
      Seq(Job(), Job(), Job())
    )
```

When looking at the mock code this goes to unwrap variarg: 
because in methodsToProcess == empty
```scala
    //For some border cases, we can't extract the varargs in the nice way, so we try the brute force one
    if (methodsToProcess.isEmpty || args.length != transformed.length) transformed
    else unwrapVarargs(transformed)
```

**Comment by borissmidt** [comment]
I suppose it is related to the variarg fix done lately and i will downgrade to 1.5

**Comment by ultrasecreth** [comment]
Hi @borissmidt , sorry for the delay, I just tried to add this test in the codebase and works like charm, would you mind posting a repo link with the failing code? (I can't seem to reproduce it otherwise)

```scala
import org.mockito.{ArgumentMatchersSugar, MockitoSugar}
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

import scala.collection.immutable.ArraySeq
import scala.concurrent.Future

class Issue378 extends AnyFlatSpec with MockitoSugar with Matchers with ArgumentMatchersSugar {

  case class Job()
  trait Logs {
    final def info(s: String): Unit = println("my hello")
  }
  class Repository extends Logs {
    def writeJobs(jobs: Seq[Job]): Future[Unit] = Future.successful(())
  }

  it should "work with varargs" in {
    val repository = mock[Repository]
    when(repository.writeJobs(*)).thenReturn(Future.successful(()))
    repository.writeJobs(ArraySeq.unsafeWrapArray(Array(Job(), Job(), Job())))
    verify(repository).writeJobs(
      Seq(Job(), Job(), Job())
    )
  }
}
```

**Comment by borissmidt** [comment]
No problem, it is used in a private repo of the company so i can't share that.
What i can tell you is that the methodsToProcess was empty in the case i changed the function ` def info(s: String): Unit = println("my hello")`  to ` final def info(s: String): Unit = println("my hello")`. but i can have another look today why it happens to give you some better info/snippet.

**Comment by ultrasecreth** [comment]
@borissmidt if `final` methods are involved, make sure you're using the `mock-maker-inline` (the standard mock maker can't deal with finals and a bunch of other things), have a look at https://github.com/mockito/mockito-scala/blob/release/1.x/scalatest/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker for reference

**Comment by borissmidt** [comment]
I guess there must have been something wrong with my dependencies. Since i can't reproduce it anymore.
Yea the weird thing with the final is that it was another method that was final, i.e. the logger library had final methods. Which cased some other code path to be taken.

**Comment by bpatters** [comment]
In case others run into this: 
I was able to reproduce this in my code and using the test above with version `1.7.1` but  upgrading to `1.17.7` fixed the issue with the test, but not my code for some reason. I'll open a new ticket if I can figure out what's different from my scenario and this test.
