### ISSUE TITLE
Answers.RETURNS_DEEP_STUBS broken in 0.4.2

### ISSUE THREAD

**Issue by Krever** [mockito/mockito-scala#38]
Hey, I would love to be able to tell more, but for now all I know is that my code that relied on 
```
val mymock = mock[MyClass](Answers.RETURNS_DEEP_STUBS)
when(myMock.someMethod.foo(any)).thenReturn(null)
```
is no longer working. Im using `MockitoFixture`. The error I get in the newest version:
```
The following invocations are unexpected (click to navigate to relevant line of code):
1. mymock.someMethod(); -> at [...]
Please make sure you aren't missing any stubbing or that your code actually does what you want
org.mockito.exceptions.misusing.UnexpectedInvocationException: Unexpected invocations found
```

This is probably somehow related to new default-default-answer but I didint have time to investigate.

**Comment by Krever** [comment]
After a little bit of investigation, the problem comes from `MockitoScalaSession` implementation. And the biggest problem is that I'm no longer able to drop-out from this behavior by using `MockitoSugar.mock` or `Mockito.mock`.

**Comment by bbonanno** [comment]
What exactly is the problem with `MockitoScalaSession`? (so I can fix it quicker)?

**Comment by bbonanno** [comment]
I found the problem, the mock returned as a deep stub was never supposed to be called on `.foo()` and because we are running on `STRICT_STUBS` it fails, it makes sense after all.

The question is, do we really want to keep silent? I mean, the whole idea of `STRICT_STUBS` is to fail in this kind of scenario when we're calling methods we didn't stub.

Or maybe for mocks created using `Answers.RETURNS_DEEP_STUBS` we actually want to move on and don't fail...

what do you think?

**Comment by Krever** [comment]
My intuition is that when someone asks for deep stubs he do this because he doesn't want to stub these things explicitly. So I would exclude all the calls covered by `deep_stubs` from verification of `strict_stubs`. But the mocks created by this deep stubs (so the result of `mymock.someMethod` in my example) should still be covered by `strict_stubs`.

**Comment by bbonanno** [comment]
The thing is you can't do that, cause sometime the user will expect to go one level deep (like your example) but some other maybe 3 or 4, so you never know where to stop and be 'strict'

I agree that if you are deliberately using 'DEEP_STUBS' you are implying that you don't want strict behaviour for that particular mock.

I'm gonna have to write my own implementation of the Answer to achieve that, I'm thinking in maybe add a configuration param for it so you can specify if you like at what level the mock has to be strict

In the meantime you can create that mock at the test class level and then reset it in an `afterEach`, I'll try to push the fix as soon as I can

**Comment by Krever** [comment]
Thanks for the workaround! 

Maybe we could somehow implement this as "if the mock was created as a deep stub, the method that caused the creation is expected to be called". Would that work?

So in
```
val mock = mock[Foo]
when(mock.m1.m2.m3.m4).then(...)
```
`mock.m1` is expected and so are invocations of `m2` and `m3` (`m4` is obvious).
