### ISSUE TITLE
Enable releases to Maven Central

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito-scala#394]
We need to enable releases to Maven Central.

Tasks:

- migrate the Gradle plugins to new Shipkit libraries, remove Bintray because it's been phased out by JFrog.
- update documentation
- enable Maven central publications

**Comment by mockitoguy** [comment]
@bbonanno, let's track the work in this ticket.

**Comment by mockitoguy** [comment]
I had some time this morning and was able to [publish a single artifact](https://s01.oss.sonatype.org/content/repositories/snapshots/org/mockito/mockito-scala_2.11/1.16-SNAPSHOT/). Still needs work but giving heads up that I'm working on it.

**Comment by DarrenBishop** [comment]
@mockitoguy any chance you can do a `+publishLocal` on that SNAPSHOT to push all cross-builds?

**Comment by DarrenBishop** [comment]
@mockitoguy also, is there anything I/the community can help with?

**Comment by mockitoguy** [comment]
I should be done with this today.

> any chance you can do a +publishLocal on that SNAPSHOT to push all cross-builds?

I believe so, we should be publishing 15 jars in total, supporting 3 Scala versions. Let me finish with this and let's chat if we need to publish more / differently.

**Comment by DarrenBishop** [comment]
Great to hear. 

Of course, I meant `+publish` earlier 😉

Confident that will be enough

**Comment by mockitoguy** [comment]
I think we should be good with the releases, right? If something is amiss please reopen!
