### ISSUE TITLE
Argument Matcher is not working for passing any[DataFrame]()

### ISSUE THREAD

**Issue by shikhil-gupta** [mockito/mockito-scala#405]
Hi Team, I am writing unit test in scala and trying to mock and stub the following function. My function takes Dataframe as input. 

  def calculateDeviceLevelAggregation(data : DataFrame) : DataFrame = {}

unit test

    val deviceHealthProfiler : DeviceOverAllHealthProfileProcessor = spy(new DeviceOverAllHealthProfileProcessor(spark, dao, any[Timestamp], any[Timestamp], 2, any[Timestamp]))

    doAnswer(new Answer[DataFrame] {
      override def answer(invocationOnMock: InvocationOnMock): DataFrame = {
        data
      }
    }).when(deviceHealthProfiler.calculateDeviceLevelAggregation(any[DataFrame]()))

But it is failing to accept any[DataFrame](). It is throwing following error

- DeviceAggregation *** FAILED ***
  org.mockito.exceptions.misusing.InvalidUseOfMatchersException: Misplaced or misused argument matcher detected here:

-> at com.microsoft.teams.deviceanalytics.core.test.DeviceOverAllHealthProfileTest$$anonfun$1.apply(DeviceOverAllHealthProfileTest.scala:21)
21/09/20 11:28:15 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
-> at com.microsoft.teams.deviceanalytics.core.test.DeviceOverAllHealthProfileTest$$anonfun$1.apply(DeviceOverAllHealthProfileTest.scala:21)
-> at com.microsoft.teams.deviceanalytics.core.test.DeviceOverAllHealthProfileTest$$anonfun$1.apply(DeviceOverAllHealthProfileTest.scala:21)

21/09/20 11:28:15 INFO MemoryStore: MemoryStore cleared
You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
21/09/20 11:28:15 INFO BlockManager: BlockManager stopped
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
21/09/20 11:28:15 INFO BlockManagerMaster: BlockManagerMaster stopped
    verify(mock).someMethod(contains("foo"))

This message may appear after an NullPointerException if the last matcher is returning an object 
21/09/20 11:28:15 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
like any() but the stubbed method signature expect a primitive argument, in this case,
use primitive alternatives.
21/09/20 11:28:15 INFO SparkContext: Successfully stopped SparkContext
    when(mock.get(any())); // bad use, will raise NPE
    when(mock.get(anyInt())); // correct usage use

**Comment by ultrasecreth** [comment]
As the error says, argument matchers are for stubbing/verification only, you're trying to use them to construct your `DeviceOverAllHealthProfileProcessor`...

**Comment by mr-git** [comment]
on which JDK version it happened? 

I observed problems with stubbing and `*[SomeType]` matchers after switching from 16 to 17

**Comment by shikhil-gupta** [comment]
> As the error says, argument matchers are for stubbing/verification only, you're trying to use them to construct your `DeviceOverAllHealthProfileProcessor`...

@bbonanno Thanks for the reply. This solves my problem.

**Comment by shikhil-gupta** [comment]
> on which JDK version it happened?
> 
> I observed problems with stubbing and `*[SomeType]` matchers after switching from 16 to 17

@mr-git I am using java 8 only.
