### ISSUE TITLE
testing private methods

### ISSUE THREAD

**Issue by ghost** [mockito/mockito-scala#53]
Hi,

Great framework. Loved knowing about it. But could not figure out how to test private scala methods? Does it support?

**Comment by Krever** [comment]
Hey, it would be reasonable to assume mockito-scala has similar limitations as mockito itself, so no, it doesnt support mocking private methods. You can check this [SO question](https://stackoverflow.com/questions/8799439/testing-private-method-using-mockito) and Powermock library mentioned there.

**Comment by ghost** [comment]
yeah!! thanks..

**Comment by ultrasecreth** [comment]
thanks @Krever, I agree, if you feel you need to mock a private method what you probably need is to refactor your code a bit in order to separate responsibilities, so then it's easier to test and reason about.
