### ISSUE TITLE
`was never called` overload has limitations

### ISSUE THREAD

**Issue by jozic** [mockito/mockito-scala#54]
Writing something like

```scala
      aMock.doSomethingWithThisIntAndString(*, "test") was never called
      aMock.doSomethingWithThisIntAndString(*, "test") was never called
```
 doesn't compile

while
```scala
      aMock.doSomethingWithThisIntAndString(*, "test") was never called
   // line break is required to compile
      aMock.doSomethingWithThisIntAndString(*, "test") was never called

```
compiles fine

![image](https://user-images.githubusercontent.com/124249/48100459-52f5ab80-e1f1-11e8-874e-5521da61e82d.png)

**Comment by jozic** [comment]
@bbonanno fyi

**Comment by ultrasecreth** [comment]
@jozic Yeah, I've seen this before somewhere else, I'm not exactly sure if it can be solved while keeping the same syntax (I wouldn't like to introduce antother breaking change)
Ideas?

**Comment by jozic** [comment]
I understand that breaking changes are bad, but non compiling code is even worse :)
and it wasn't like I figured out the solution in 5 seconds, I was almost at the point to give up

so i personally think it should be fixed at any cost, but of course this is just my opinion

**Comment by ultrasecreth** [comment]
The problem is that the postfix notation can not always infer where the `;` goes, that's one of the reasons why it's hidden behind a feature flag

my point is I'm not sure how to re-write the 3 use cases in case that's the only solution, i.e.

```
mock1.bar was called
mock1.bar was never called
aMock was never called again
```

How can we semantically re-write those 3 while keeping an english syntax that makes sense

**Comment by jozic** [comment]
`was never calledAgain`? `was neverCalled again`?
it looks worse then all words separately, but we already sort of have similar case with `was called` and `wasCalled once`

**Comment by ultrasecreth** [comment]
@jozic not sure if you get the notifications for the PR #56, so just in case I drop this "please check it out here" :)
