### ISSUE TITLE
HttpExt.singleRequest with implicit parameters can not be mocked

### ISSUE THREAD

**Issue by gadcam** [mockito/mockito-scala#58]
If I try to mock the object <code>HttpExt</code> (imported like this <code>import akka.http.scaladsl.HttpExt</code>) it will not work with this library.
This one will mock the object
```scala
import akka.http.scaladsl.HttpExt
import org.scalatest.mockito.MockitoSugar.mock
...

val mockHttp = mock[HttpExt]
```

this one will not work i.e. it will just return an instance of HttpExt and not a mock
```scala
import akka.http.scaladsl.HttpExt
import org.mockito.MockitoSugar.mock

...

val mockHttp = mock[HttpExt]
```

I also could not spy an HttpExt instance.

I am using 
```sbt
"org.mockito" % "mockito-scala_2.12" % "1.0.1"
```
and

```sbt

"org.scalatest" % "scalatest_2.12" % "3.0.5" % "test"
```

**Comment by ultrasecreth** [comment]
Hi @gadcam 
I just tried the following and it worked

```scala
    "work with HttpExt" in {
      val httpMock     = mock[HttpExt]
      val mockedResult: ClientLayer = BidiFlow.identity[HttpRequest, SslTlsOutbound].asInstanceOf[ClientLayer]

      httpMock.clientLayer(*) shouldReturn mockedResult

      httpMock.clientLayer(Host("localhost", 80)) should be theSameInstanceAs mockedResult

      httpMock.clientLayer(Host("localhost", 80)) was called
    }
```

Could you provide a full example so I can try to reproduce it?

That said, it's usually a code smell/anti-pattern to mock classes you don't own, why is that you need to mock `HttpExt` and not something you own and that uses `HttpExt` underneath?

**Comment by gadcam** [comment]
Hi @bbonanno,
Thank you for your very quick answer. I am really sorry my first post was very innacurate, feel free to rename the issue.
I thought the problem was broader than I think now as the debugger was showing me that the object <code>httpMock</code> was **not** a mock.

So here is my Minimal, Complete, and Verifiable example.

MainTest.scala
```scala
import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global

import akka.http.scaladsl.{HttpExt, HttpsConnectionContext}
import akka.http.scaladsl.model._
import akka.http.scaladsl.settings.ConnectionPoolSettings
import akka.event.LoggingAdapter

import org.scalatest.{Assertion, Matchers, WordSpecLike}
import org.mockito.ArgumentMatchersSugar
import org.mockito.MockitoSugar.doReturn

class MainTest extends WordSpecLike
  with Matchers
  with ArgumentMatchersSugar {

  val randomRequest = HttpRequest()
  val response = Future(HttpResponse())

  def testMock(mockHttp: HttpExt): Assertion = {
    doReturn(response)
      .when(mockHttp)
      .singleRequest(any[HttpRequest], any[HttpsConnectionContext], any[ConnectionPoolSettings], any[LoggingAdapter])

    mockHttp.singleRequest(randomRequest) should be theSameInstanceAs response
  }

  "mock" should {
    "should work if coming from scalatest" in {
      val mockHttp = org.scalatest.mockito.MockitoSugar.mock[HttpExt]

      testMock(mockHttp)
    }
    "should work if coming from mockito" in {
      val mockHttp = org.mockito.MockitoSugar.mock[HttpExt]

      testMock(mockHttp)
    }
  }
}
```

The library I import
```sbt
libraryDependencies += "org.mockito" % "mockito-scala_2.12" % "1.0.1"
libraryDependencies += "org.scalatest" % "scalatest_2.12" % "3.0.5"
libraryDependencies += "com.typesafe.akka" %% "akka-http" %  "10.1.5"
libraryDependencies += "com.typesafe.akka" %% "akka-http-testkit" %  "10.1.5"
libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.5.17"
```

And it will throw something beginning by
```
You have a NullPointerException here:
-> at akka.http.scaladsl.HttpExt.singleRequest$default$4(Http.scala:687)
because this method call was *not* stubbed correctly:
-> at akka.http.scaladsl.HttpExt.singleRequest$default$4(Http.scala:687)
httpExt.system();

org.mockito.exceptions.verification.SmartNullPointerException: 
You have a NullPointerException here:
-> at akka.http.scaladsl.HttpExt.singleRequest$default$4(Http.scala:687)
because this method call was *not* stubbed correctly:
-> at akka.http.scaladsl.HttpExt.singleRequest$default$4(Http.scala:687)
httpExt.system();
```

**Comment by ultrasecreth** [comment]
@gadcam The problem is that mockito-scala is aware of default arguments, if you look at the signature of `singleRequest` it looks like
```scala
  def singleRequest(
    request:           HttpRequest,
    connectionContext: HttpsConnectionContext = defaultClientHttpsContext,
    settings:          ConnectionPoolSettings = defaultConnectionPoolSettings,
    log:               LoggingAdapter         = system.log): Future[HttpResponse]
```

Now, the `log` parameter receives as default `system.log`. As `system` hasn't been stubbed, mockito-scala will return a SmartNull (a mock that will fail if you call any method on it) which is the one that is throwing that exception you see...

You have many ways to overcome this, but probably the easiest is to pass a mock of a `LoggingAdapter` to the `singleRequest` method so the default value is not used...

BTW, your code would look much cleaner with the new API, e.g.

```scala
  val randomRequest = HttpRequest()
  val response      = Future(HttpResponse())
  "mock" should {
    "should work if coming from mockito" in {
      val mockHttp = mock[HttpExt]
      val logger   = mock[LoggingAdapter]

      mockHttp.singleRequest(*, *, *, *) shouldReturn response

      mockHttp.singleRequest(randomRequest, log = logger) should be theSameInstanceAs response
    }
  }
```

**Comment by gadcam** [comment]
@bbonanno Thank you for the clarification.
Do you know why Mockito in scalatest does handle this case ?

Thank you for the advice I will use the new API.

**Comment by ultrasecreth** [comment]
@gadcam It actually doesn't
For starters, Scalatest doesn't provide any mocking library, it only wraps the `mock` method with a nicer syntax, but you are 100% using the Java Mockito.
Java Mockito is completely oblivious to default arguments (and any other Scala-only feature), from the Mockito point of view, they are null if you don't provide them (you can check this by writing a `verify` to see what arguments were passed to the method). You can find a more detailed explanation [here ](https://medium.com/@bruno.bonanno/introduction-to-mockito-scala-ede30769cbda)

**Comment by gadcam** [comment]
@bbonanno Thank you for your patience.
So now as I understand it: the example I gave was only working thanks to a side-effect of using Java Mockito.

In my code the situation is a bit more complex : an actor is using the mockHttp object, as a consequence I can not override the default argument.

I solved it by passing the system object to the mock

```sbt
system willBe returned by mockHttp.system
```

Please note that in a non-test code it would be passed as an implicit argument
