### ISSUE TITLE
Macro expansion failure with HigherKinds

### ISSUE THREAD

**Issue by RawToast** [mockito/mockito-scala#66]
I use helpers in my tests to keep things clean such as:

```
def whenGetById[F[_]](implicit algebra: MyAlgebra[F]): OngoingStubbing[F[Either[MyError, MyResult]]] =
    when(algebra.get(anyVal[My.Id])).delegate

// or on later versions
def whenGetById[F[_]](implicit algebra: MyAlgebra[F]): OngoingStubbing[F[Either[MyError, MyResult]]] =
    when(algebra.get(any[My.Id])).delegate
```

This worked fine from `0.4.4` (obviously without the delegate call) to `1.0.2`. However upon upgrading to any version past `1.0.3` my tests now fail to compile:

```
[error] /***/MockServices.scala:15:46: exception during macro expansion: 
[error] scala.ScalaReflectionException: type F is not a class
[error]         at scala.reflect.api.Symbols$SymbolApi.asClass(Symbols.scala:272)
[error]         at scala.reflect.api.Symbols$SymbolApi.asClass$(Symbols.scala:272)
[error]         at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:94)
[error]         at org.mockito.internal.ValueClassExtractor$.materialise(ValueClassExtractor.scala:36)
[error]     when[F[Either[MyError, MyResult]]](merchants.get(anyVal[My.Id])).delegate
```

Currently I have to work around this with the following method, which allows me to use `1.0.5`, but I lost any benefits of using the `ScalaOngoingStubbing`

```
private def hkWhen[T](methodCall: T): OngoingStubbing[T] = Mockito.when(methodCall)
```
I presume this is related to the `ValueClassExtractor` requirement added to when, which does not work for the `F` HigherKind.

Moreover, since version `1.0.2`? my tests have started spitting out dead code errors on `when` conditions with value classes -- despite stating the types.

**Comment by ultrasecreth** [comment]
@RawToast Thanks for reporting this, v1.0.6 should fix it, please let me know otherwise

Regarding the dead code errors, I don't have the flag enabled as most of the code throws it so it's too much noise for me, but I can take a look as in theory it shouldn't happen if you specify the types, could you please create a separate issue with a full example that I can copy and paste to reproduce the problem?

Thanks

**Comment by RawToast** [comment]
@bbonanno Thanks, that fixed my issue and I no-longer need to use `delegate`. This is the structure I've been using, which works beautifully now 😄I'll extract a full example when I get time and see if the dead-code error is something more specific:

```
def whenGet[F[_]](implicit algebra: MyAlgebra[F]): ScalaFirstStubbing[F[Either[MyError, MyResult]]] =
    when(algebra.get(any[My.Id]))

implicit class StubbingSyntax[F[_], L, R](
    val stubbing: ScalaFirstStubbing[F[Either[L, R]]]
  )(
    implicit
    A: Applicative[F]
  ) {
    def thenReturn(response: R): ScalaOngoingStubbing[F[Either[L, R]]] =
      stubbing.thenReturn(A.pure[Either[L, R]](Right[L, R](response)))

    def thenFail(error: L): ScalaOngoingStubbing[F[Either[L, R]]] =
      stubbing.thenReturn(A.pure[Either[L, R]](Left[L, R](error)))
  }
```

**Comment by ultrasecreth** [comment]
@RawToast I'm glad it worked!

That syntax looks interesting, could you post an example of a test using it? I wanna see if it could be worth to incorportate it (or part of it) directly into the library

Some questions in the meantime 

is `My.Id` a value class?
why are you mocking an algebra? and wy it's implicit?
how do you define the Applicative in the test?

Cheers

**Comment by RawToast** [comment]
`My.Id` is a value class.

We mock an algebra to test some steps in a process that uses multiple algebras. So depending on the response from an algebra's method, we may have two do something different -- or short circuit. Mockito is used for verification -- but it could definitely be done differently 😄

The applicative is just brought in from Cats within the test.

It's implicit to make life easier and the tests cleaner. e.g. you can just write code like:

```
import cats.instances.option_._
implicit val catCrudAlgebra[F] = mock[CatCrud[Option]] // The real service would be using a Future, Task, etc
implicit val rescueHomeAlgebra[F] = mock[RescueHomes[Option]]
implicit val councilService[F] = mock[CouncilService[Option]]

val catProcessor = CatProcessor[F](catCrudAlgebra, rescueHomeAlgebra, councilService)

whenCreateCat.thenReturn(Unit)
whenGet.thenReturn(myCat)
whenAddingCatToRescueHome.thenFail(CatDoesNotExistError)
whenInformingCouncil.thenReturn(Unit)

val result = catProcessor.addNewCatToStraysRescueHome(myCat, myStraysRescue).get
// Now verify the result and verify any interactions (probably, in this case that the councilService isn't interacted with)
```

**Comment by ultrasecreth** [comment]
@RawToast I see, I got confused cause in my understanding, an algebra is a group of case classes and/or instances of sealed traits, which don't make a great candidate for mocking, but in your case, you're mocking services, which is what mocks are for :)

I'll have a look to see if this could be built in a more generic way, as here everything but the `Either` seems configurable
