### ISSUE TITLE
Fix Maven pom problems

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito-scala#7]
Generated pom.xml file should meet all requirements of Maven Central. Here's the validation error I saw when attempting to sync mockito-scala to central:

```
Last Sync Errors: Invalid POM: /org/mockito/mockito-scala_2.12/0.0.5/mockito-scala_2.12-0.0.5.pom: Project URL missing, License information missing, SCM URL missing, Developer information missing Dropping existing partial staging repository.
```

@bbonanno, can you take a look at it? Thanks!

**Comment by bbonanno** [comment]
@mockitoguy #8 should do the trick (I hope, can't test it)

Cheers

**Comment by mockitoguy** [comment]
Looks good! I've exported the env variables (nexus user and password) to the Travis CI repo. This way, we will get automated publications to central every merged pull request :)

**Comment by bbonanno** [comment]
@mockitoguy Amazing!

Now to spread the word!
