### ISSUE TITLE
Verification on mock object not respect to test case

### ISSUE THREAD

**Issue by mesut** [mockito/mockito-scala#74]
Problem:

Let's say we have two different service

```
class ServiceA(serviceB: ServiceB) {

  def methodA(): String = {
    "methodA called"
    serviceB.methodB()
  }

  def methodA2(): String = {
    "methodA2 called"
    serviceB.methodB()
  }
}

```
I write two test method and try to verify methodB called or not. When I run two test cases separately, tests pass. When I run all test methods, verification gives wrong result for second test. 
In test class context, mockito-verification records all calls on mock object. I think mockito-scala should reset verification counts on mock objects after each test

```
class ServiceATest extends FlatSpec with IdiomaticMockito {
  val serviceB: ServiceB = mock[ServiceB]
  val serviceA: ServiceA = new ServiceA(serviceB)
  "methodA" should "called" in {
    serviceA.methodA()
    serviceB.methodB wasCalled once // Passes
  }
  "methodA2" should "called" in {
    serviceA.methodA2()
    serviceB.methodB wasCalled once // Fail. it was 2 times:
  }
}
```

Btw I tried with mockito-core, it gives same error.

**Comment by ultrasecreth** [comment]
That's rather an issue related to how Scalatest works compared to JUnit, in JUnit the runner will create an instance of the test class for every test, while Scalatest creates just one and re-uses it for every test, so if you have any kind of mutable object declared at the class level you're re-using them in each test.

The standard way to solve it is to use an inner trait, thus re-writing your test like

```scala
class ServiceATest extends FlatSpec with IdiomaticMockito {
  trait Setup {
    val serviceB: ServiceB = mock[ServiceB]
    val serviceA: ServiceA = new ServiceA(serviceB)
  }
  "methodA" should "called" in new Setup {
    serviceA.methodA()
    serviceB.methodB wasCalled once
  }
  "methodA2" should "called" in new Setup {
    serviceA.methodA2()
    serviceB.methodB wasCalled once 
  }
}
```

Now, if for any reason you **must** declare your mocks at the class level (like if you are passing them to Play! or something like that) you can resort to [ResetMocksAfterEachTest](https://github.com/mockito/mockito-scala#orgmockitointegrationsscalatestresetmocksaftereachtest) which just by being mixed in will reset the mocks after each test.

As a rule of thumb I'd encourage to use the first solution as it also ensures that any common dependency your tests may have will be created independently for each one of them, thus providing test isolation which is very important when working unit tests.

**Comment by mesut** [comment]
Thank you very much!
