### ISSUE TITLE
Return different values when using "willBe returned by"

### ISSUE THREAD

**Issue by estebanbolanos** [mockito/mockito-scala#86]
I am just learning mockito-scala, and I am trying to apply the [idiomatic style](https://github.com/mockito/mockito-scala#idiomatic-mockito) guided by the project documentation.

For some tests, I need to make a _spy_ return different values for each invocation, in order to verify that a retry mechanism is working (i.e., I want to verify that my application will keep trying until an "OK" response is returned by an external system.)

On the documentation, I can see that the idiomatic syntax would allow me to do that with **shouldReturn**:

`aMock.bar shouldReturn "mocked!" andThen "mocked again!"`

But I cannot find an example on the documentation (or elsewhere) about how to do that with **willBe returned by**, which is the specific style I have been using successfully in my test cases. Here's the example provided by the documentation for a single return value:

`"mocked!" willBe returned by aMock.bar`

Is it possible to have the _spy_ return a different value for each invocation when using **willBe returned by**? If it is, perhaps a corresponding example could be added to the documentation, or else a note indicating that it is not feasible.

**Comment by ultrasecreth** [comment]
Hi @estebanbolanos 
Thanks for the heads up, you are correct, the syntax does not support that, the reason being it's quite tricky to do so and usually in Scala you want referential transparency, so the same function should always return the same result for the same input, but it seems that yours is a valid use case, I'll add the note in the docs.

To solve your issue you currently have 2 options
- Use the old syntax for that particular stub
- Use an answer that knows what to do, i.e if I want it to fail 3 times
```scala
      var invocationCounter: Int = 0
      { () =>
        invocationCounter = invocationCounter + 1
        if(invocationCounter) <= 3 fail() else sucess()
      } willBe answered by aSpy.doSomethingWithThisInt(*)
```
Not the prettiest code, but it should do what you want

**Comment by ultrasecreth** [comment]
Documentation updated.
