### ISSUE TITLE
Can not capture argument with ArgCaptor[Any]

### ISSUE THREAD

**Issue by sohoffice** [mockito/mockito-scala#89]
With the following version:

- mockito-scala: v1.2.4
- mockito: 2.24.0
- Scala: 2.12.4

An `ArgCaptor[Any]` fails to capture, but `ArgumentCaptor.forClass[Any, Any](classOf[Any])` is fine.

The below fails at runtime:

```
val ac5 = ArgCaptor[Any]
verify(scheduler).scheduleOnce(any[Duration], eqTo(topicActor), ac5)(any[ExecutionContext], any[ActorRef])

// Emits the following exception
   Invalid use of argument matchers!
   5 matchers expected, 4 recorded:

// This can be fixed by replacing ac5 with any[Any].
// But I need to capture that argument and validate.
```

#### Details

The method signature of scheduleOnce as the below.
There're override variances, but this is the one with correct argument count and type.
The source code of this method can be found [here](https://github.com/akka/akka/blob/v2.5.11/akka-actor/src/main/scala/akka/actor/Scheduler.scala).

```
  final def scheduleOnce(
    delay:    FiniteDuration,
    receiver: ActorRef,
    message:  Any)(implicit
    executor: ExecutionContext,
                   sender: ActorRef = Actor.noSender): Cancellable
```

#### Workaround

```
// The generic type has to be explicit otherwise it won't compile
val ac5a = ArgumentCaptor.forClass[Any, Any](classOf[Any])

verify(scheduler).scheduleOnce(any[Duration], eqTo(topicActor), ac5a.capture())(any[ExecutionContext], any[ActorRef])
```

**Comment by ultrasecreth** [comment]
@sohoffice Can you post the signature of `scheduleOnce` please

**Comment by sohoffice** [comment]
@bbonanno I've updated the issue description to add the signature and the link to the source code of that method on github (if you need to cross check the other variances of this method)

**Comment by ultrasecreth** [comment]
@sohoffice The problem here is related to the fact that `sheduleOnce` has `Any` as the argument type that you want to capture, so the `implicit` conversion that automatically does the capture
```scala
implicit def asCapture[T](c: Captor[T]): T = c.capture
```
is not called as the compiler finds no need to convert `Captor[Any]` into `Any`, as it is already an instance of `Any`, given that `Any` is the parent of every type in Scala. Because of that, the type does not need any transformation to be passed in.

The solution here in your example is to call `capture` manually on your verification
```scala
val ac5 = ArgCaptor[Any]
verify(scheduler).scheduleOnce(any[Duration], eqTo(topicActor), ac5.capture)(any[ExecutionContext], any[ActorRef])
```

**Comment by ultrasecreth** [comment]
@sohoffice and BTW, to avoid future problems, remove any mockito dependency that is not mockito-scala

**Comment by ultrasecreth** [comment]
And as final suggestion (after updating to v1.2.5), I'd re-write that code to use the idiomatic syntax so it's less boilerplatish and easier to read

```scala
val ac5 = ArgCaptor[Any]
scheduler.scheduleOnce(*, topicActor, ac5.capture)(*, *) was called
```

**Comment by sohoffice** [comment]
Thanks for this. Upgraded to 1.2.5, all is well.

Looks like I'll need to remember to use capture when I want an Any value captured, or perhaps I'll always call capture ? This matches the behavior of mockito, perhaps not all that bad IMHO.

I love how a tiny * can replace the any[ReallyLongType] call. I'm at the moment very struggling on whether to switch to the idiomatic syntax. I usually would prefer the old syntax for being able to wrap and indent the line wherever I wanted. But it seems the little nice * can not work along with given value without eqTo(). That is, too unfortunate the following won't work:

```
// topicActor must be wrapped with eqTo
verify(scheduler).scheduleOnce(*, topicActor, ac5.capture)(*, *)
```

This is a great project, it makes using mockito with scalatest a great joy. Thanks again.

**Comment by ultrasecreth** [comment]
@sohoffice Yes, the ability to mix matchers and raw arguments only works when using the idiomatic syntax.

Glad to hear you like it!
